import pandas as pd
import numpy as np

Row(CLUSTER_FLD, TIPO_ENVIO, DATA_ENVIO, DIA_SEMANA, UTM_CAMPAIGN, SUBJECT, PRE_HEADER, UTM_SOURCE, UTM_MEDIUM, UTM_TERM, UTM_CONTENT, TEMPLATE, CICLO_VIDA, ENGAJAMENTO_ABERTURA, ENGAJAMENTO_CLIQUES, PRIMEIRA_VITRINE, SEGUNDA_VITRINE, TERCEIRA_VITRINE, CHAMADA_VITRINE_1, CHAMADA_VITRINE_2, TIPO_BANNER, NOME_BANNER, TEXTO_CHAMADA, TITULO, TEXTO_APOIO, ATRIBUTOS, TITULO_LINHA, CTA, URL, FILTRO,
    LINK_ORIGEM, TEXTO_LEGAL, COMENTARIOS, LOGO_LINK='CPC7,,24/09/2021,sexta-feira,ncf_bra_email_cco_d_prd_CPC7-Geral-comercial-par_cliq90aber90_tododia_20210924,O melhor mï¿½s chegou!!,E trouxe atï¿½ 55% OFF no Esquenta Natura Friday!,cf_cco,news,x,CPC7,comercial-par,Geral,90,,PROMOCAO,CUIDADOS DIARIOS,PERFUMARIA FEMIN,Produtos e preï¿½os que vocï¿½ vai amar:,,ENGAJAMENTO,,,,,,,,,,,,,www.natura.com.br')
